### ISSUE TITLE
Issues integrating

### ISSUE THREAD

**Issue by leemorse** [team-moeller/better-access-charts#102]
Hi,

I'm having issues with integrating. Here is my code:

```
QUICK_RATIO_CHART_SQL = "SELECT [Quick Ratio] FROM [RATIO ANALYSIS] WHERE [ASX Code] like '" & ASXCODE & "'
Set QR_Chart = BAC.Chart(Me.wbChartQR)
QR_Chart.CreateChart
QR_Chart.DataSource.SQLStatement = QUICK_RATIO_CHART_SQL
QR_Chart.DataSource.DataFieldNames = Array("Quick Ratio")
QR_Chart.ChartType = chChartType.Line
```
When the chart displays is shows only the Demo Data as a bar graph.

Are there any obvious issues?

Thank you

**Comment by team-moeller** [comment]
Hi there!
I see some reasons here for the trouble you have:

* In row 3 you create the chart without further specifications. This will always lead to the demo chart. Put this row at the end
* In the SQL-Statement you have only one field (for the data I think). You also have query the label field.
* At the end you must tell the chart the name of the label field.

I've adapted your code to the data in the sample database. In the end my code looks like this:
```
    Dim QR_Chart As BAC_Chart
    Dim QUICK_RATIO_CHART_SQL As String

    QUICK_RATIO_CHART_SQL = "SELECT DataLabel, [Dataset1] FROM [tbl_DemoData] WHERE 1=1"
    Set QR_Chart = BAC.Chart(Me.wbChartQR)
    QR_Chart.DataSource.SQLStatement = QUICK_RATIO_CHART_SQL
    QR_Chart.DataSource.DataFieldNames = Array("Dataset1")
    QR_Chart.DataSource.LabelFieldName = "DataLabel"
    QR_Chart.ChartType = chChartType.Line
    QR_Chart.CreateChart
```
I will close this issue.
