### ISSUE TITLE
Regional Settings - decimal and list separators

### ISSUE THREAD

**Issue by dagnachewl** [team-moeller/better-access-charts#103]
Hi there,

Many thanks for this excellent solution.
Is there a simple way to handle decimal and list separators other than the default US system?
I'm currently using a simple search-replace custom function for decimal separator and use comma for lists when creating the data list like so

myChart.DataSourceObjectName = "SELECT *, IIf(lngAnalysisID IS NULL, '', '{x:' & fstr_ReturnWithDecimalPoint(O18) & ', y:' & fstr_ReturnWithDecimalPoint(H2) & '}') As data1
...

Public Function fstr_ReturnWithDecimalPoint(ByVal pstr As String) As String
 ......
   sz = Trim$(CStr(3 / 2)) 
    Select Case sz
      Case "1,5"
        'Replace each comma by a point.
        int_1 = InStr(1, pstr, ",")
        Do Until int_1 = 0
          Mid(pstr, int_1, 1) = "."
          int_1 = InStr(1, pstr, ",")
        Loop
....

Thanks!

**Comment by team-moeller** [comment]
I think this is a general question that has nothing directly to do with Better Access Charts. So I will close this issue.
Have you ever thought about using the Replace function?
