### ISSUE TITLE
Get this error 3004

### ISSUE THREAD

**Issue by gsasoftware** [team-moeller/better-access-charts#106]
![Captura](https://user-images.githubusercontent.com/355667/186541440-9699d995-5c3c-4496-ade9-8a6a8a7dc03b.PNG)
e

**Comment by team-moeller** [comment]
The information is a little skimpy. Perhaps you can describe in detail under what circumstances the error occurs.
And a translation in English will be nice. 👍

**Comment by gsasoftware** [comment]
Solved

**Comment by team-moeller** [comment]
@gsasoftware 
Can you please describe what the problem and what the solution was. This will help further users.
TIA

**Comment by gsasoftware** [comment]
2 times the same mychart.createchart in the same module
