### ISSUE TITLE
Script Error 

### ISSUE THREAD

**Issue by Rahmania333** [team-moeller/better-access-charts#107]
![CamScanner 09-13-2022 09 02](https://user-images.githubusercontent.com/79392571/189804877-7fa906e3-d808-4581-a0a5-6e470ddd61b9.jpg)

Hello everyone
I have an error with better excess chart database
When I click create chart button the following warning appears

Script Error

An error has occurred in the script on this page.

Line: 18

Char: 5

Error: 'Chart' is undefined

Code: 0

URL: file:///C:/Users/Software House%% 20Buner/AppData/Local/Temp/BetterAccessChart_372909976.html

Do you want to continue running scripts on this page?

Yes

ON

I have tried it on both Windows 10 and Windows 11
I am beginners if someone can help me please
Thanks in advance

**Comment by Rahmania333** [comment]
@KDGundermann @sten-schmidt @team-moeller @NaincyKumariKnoldus

**Comment by team-moeller** [comment]
Hi @Rahmania333 ,
this error can have different causes. When does the error occur? After integration into your own database? Or when calling from the demo database? What settings have you made?
Regards

**Comment by Rahmania333** [comment]
Hello @team-moeller Thank you so much for your reply
first time Demo Database was working fine. then I tried Charts from my own Tables according to the instructions given on the website it was also working fine. but now neither the demo database is working nor my own. and the above warning appears
and did not make any change in the modules.
please help me i am very disappointed.

**Comment by team-moeller** [comment]
OK, so it basically worked before. So now we have to see what's going wrong.
Can you take a closer look at the html file that is mentioned in the error message. Maybe you will get concrete hints if you open them in the browser. At the latest when you switch on the developer tools there with F12, I would expect an error message.

**Comment by Rahmania333** [comment]
@team-moeller 
![Html File](https://user-images.githubusercontent.com/79392571/190834185-6af8a46b-6e7d-41de-b146-1805e57bac67.png)


This is the screen shot
bundles of thanks

**Comment by Rahmania333** [comment]
Thanks for giving time @team-moeller 

This is the screenshot of html file

![Html File](https://user-images.githubusercontent.com/79392571/190834525-28540948-36f4-4416-b751-1b5c21405ea0.png)

**Comment by Rahmania333** [comment]
Thanks for giving time @team-moeller 

This is the screenshot of html file

![Html File](https://user-images.githubusercontent.com/79392571/190834762-3da4b851-c002-468d-b051-533e860d5038.png)

I searched for the solution
Here is the link 🔗
https://stackoverflow.com/questions/29785623/referenceerror-chart-is-not-defined-chartjs
But i didn't understand please help

**Comment by Rahmania333** [comment]
🙄

**Comment by team-moeller** [comment]
Sorry, I was on a short vacation.
Please attach the html-file so I can try it on my machine.

**Comment by Rahmania333** [comment]
Here it is

**Comment by team-moeller** [comment]
I cannot find an attachment.
Are you sure you have attached the html-file?

**Comment by Rahmania333** [comment]
BetterAccessChart_2967539825312.html
<https://drive.google.com/file/d/188Kheuc_-q7L2eIdgK4GiwQC873kOs8w/view?usp=drivesdk>

**Comment by team-moeller** [comment]
I just downloaded your file and it opened without problems. So the file itself is OK.

Question: Do you have active browser add-ons that block Javascript, such as NoScript or uBlock?

What happens when you try a "curl" with the link to the javascript library?

![CURL](https://user-images.githubusercontent.com/74451434/191578425-4d088176-99b3-423b-8126-9cfb9fb1b59d.png)

I hope that you can find a solution with these tips. Otherwise you should contact one of the many forums on the web with your problem.

This is not a problem with Better Access Charts, this is a problem on your machine accessing the Chart.js library. For this reason I am closing this issue.

**Comment by Rahmania333** [comment]
💕
