### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by Rahmania333** [team-moeller/better-access-charts#119]
![16775526856107297692658839301154](https://user-images.githubusercontent.com/79392571/221741132-2c084923-9e4b-4ada-9be5-f6d40e7640d8.jpg)

**Comment by Rahmania333** [comment]
On this startup I see this error
As a beginner I didn't understand
Please help me.

**Comment by team-moeller** [comment]
Can you please provide a few additional information's?
Can you please download the last release, unblock the file, open it in Access.
Do you see a welcome screen? What happens when you click the OK button?

**Comment by Rahmania333** [comment]
Sorry @team-moeller  for late reply . I did not receive notification 
I have downloaded the latest Version When i Double click the MS Access File I see this Massage
![Error](https://user-images.githubusercontent.com/79392571/224469205-95e95d83-5c6c-4406-b39d-e24de8ee20ea.png)
No Welcome Screen, No unblock warning but when i click ok then welcome screen appear
after clicking "Open Demo" Button i see the message box 
![error2](https://user-images.githubusercontent.com/79392571/224469207-f143f495-54f0-431a-8384-332edc5e4719.png)
on compiling no error appear

**Comment by team-moeller** [comment]
Some ideas:
- Check the references to see if one is broken
- do you run Access 64 bit?
- uncomment the code in Form_Load of frm_Startup and see what happens

**Comment by Rahmania333** [comment]
no broken reference 






![err0r3](https://user-images.githubusercontent.com/79392571/224470185-ef25f2c3-ef8a-43ca-986f-9384683eff72.png)





Yes I use Access 64 bit

by uncomment the code in Form_Load of frm_Startup nothing happened

 importing all objects not working

**Comment by team-moeller** [comment]
I think we have the reason: My demo database is built with Access 32 bit. and you use Access 64 bit.
I have never dealt with Access 64 bit, so I don't know what to recommend at the moment.

**Comment by Rahmania333** [comment]
@team-moeller  Thank you for giving time
i love your work and i will search for the solution
if you find it please mention it

**Comment by Rahmania333** [comment]
@team-moeller  can you please send me the screen shot of references

**Comment by team-moeller** [comment]
The references dialog on my computer looks exactly the same:

![image](https://user-images.githubusercontent.com/74451434/224473408-4f428c91-1c5f-4816-ab6b-d7fe8ea1a21f.png)

**Comment by Rahmania333** [comment]
@Noson5434
Not working for me. ,,😞😭

**Comment by Noson5434** [comment]
Maybe try decompiling...

I'll be at my PC later and I will send you the working application and see if it will work for you.

**Comment by Noson5434** [comment]
@Rahmania333 
Try this.

[Better-Access-Charts.zip](https://github.com/team-moeller/better-access-charts/files/11099808/Better-Access-Charts.zip)

**Comment by Rahmania333** [comment]
@Noson5434 
Same issue
Same warning message

**Comment by team-moeller** [comment]
Hi @Rahmania333 !
Do you still have this issue?
Otherwise I would like to close this one.

**Comment by team-moeller** [comment]
After two weeks with no response I close this issue.
