### ISSUE TITLE
Allow to configure animations

### ISSUE THREAD

**Issue by KDGundermann** [team-moeller/better-access-charts#121]
requested in AEU 02/2023

**Comment by team-moeller** [comment]
Hi @KDGundermann ,
I am not sure what you mean with the request.
It is possible to configurate the Duration and the Easing of the animations:
![image](https://user-images.githubusercontent.com/74451434/225701866-b077b8e4-b566-4f63-bd38-a21a3cf03058.png)

**Comment by KDGundermann** [comment]
Sorry Thomas,
I'm getting old. Could not remember that the function is already there.

**Comment by team-moeller** [comment]
@KDGundermann 

> Sorry Thomas, I'm getting old. 

You are not alone. 😊
