### ISSUE TITLE
Pie chart data label

### ISSUE THREAD

**Issue by clm66** [team-moeller/better-access-charts#139]
Hi -
I have a pie chart and want to display not the values on the pie pieces but the fields.
E.g. if I have a distribution of Europe = 70 % and Asia = 30 % - I want to see "Europa" and "Asia" on the pie pieces.
Is this possible?

Thanks, Claus

**Comment by team-moeller** [comment]
As far as I know, the plugin for the data labels, which is used here, is only able to output the numerical values.
The descriptions you would like to see are in the legend.
