### ISSUE TITLE
Custom Names of Datasets in Legend

### ISSUE THREAD

**Issue by PacManPk** [team-moeller/better-access-charts#143]
Hello,

It would be useful if an option to add custom labels/names for datasets in legend is added. Right now it ises field name for the dataset name in legend. It could selected like we select array of DataFieldNames.

Best Regards

**Comment by team-moeller** [comment]
Hi @PacManPk, 
have you considered to use a query instead of a table as data source.
There you can give an alias for each field name.
This could be the text you would like to see in the legend.
If this is suitable for you drop me a line so I can close this issue.

**Comment by PacManPk** [comment]
Thanks for reply. Yes I used query and also achieved the desired results. I suggested this so that one can use directly names. You can close this issue if it doesn't seem useful.
