### ISSUE TITLE
Using WebBrowser control / Access 2013 runtime

### ISSUE THREAD

**Issue by arielcortez** [team-moeller/better-access-charts#187]
This does not work on access 2013 runtime.  is it possible to run this using Access 2013 runtime?  Since many of deployed machines have MS office using MSI installation instead of click to run tech. it is not possible to install access 365/2021 runtimes together with ms office 2021 and 2019. so most of deployments need to be in 2013 runtime.  i believe lower version of chart js 3.3x/ 2.9x or lower supports IE11 and can it have a version that renders chartjs charts using the webbrowser control instead of edge browser?  thanks in advance.

**Comment by team-moeller** [comment]
Please have a look at this site in the wiki: [Available Versions](https://github.com/team-moeller/better-access-charts/wiki/available-versions)
The last version of Better Access Charts running with the old legacy webbrowser control is version [2.31.03](https://github.com/team-moeller/better-access-charts/releases/tag/2.31.03).

You can find a detailed explanation on this blog post: [Better Access Charts: Versuche mit Chart.js 3 und höher](https://blog.team-moeller.de/2023/02/better-access-charts-versuche-mit.html).
(The content is original in German but with today's tools it should be no problem to get a proper translation.)
