### ISSUE TITLE
Support 64-bit versions of Access

### ISSUE THREAD

**Issue by mwolfe02** [team-moeller/better-access-charts#20]
When compiling the demo database in 64-bit versions of Access, one receives the following error:

![image](https://user-images.githubusercontent.com/305213/100548527-19aa9100-323b-11eb-8a2a-eac8bc1411b6.png)

**Comment by mwolfe02** [comment]
The only problem appears to be with the DLL call at the top of the mdl_Helpers module.

Here's a fix that is compatible with prior versions of Access that are 32-bit only:

```vba
#If VBA7 Then
    Private Declare PtrSafe Function MakeSureDirectoryPathExists Lib "imagehlp.dll" (ByVal lpPath As String) As Long
#Else
    Private Declare Function MakeSureDirectoryPathExists Lib "imagehlp.dll" (ByVal lpPath As String) As Long
#End If
```

**Comment by mwolfe02** [comment]
Great project, by the way :wink:

**Comment by team-moeller** [comment]
Thanks for the hint. I did not think about that.
The crazy thing is that the declaration that is causing the error is not needed for the core project.

**Comment by team-moeller** [comment]
Thanks for the hint. I did not think about that.
The crazy thing is that the declaration that is causing the error is not needed for the cproject.

**Comment by team-moeller** [comment]
code is changed
will be shipped with the next release
