### ISSUE TITLE
Getting this to work with Chartjs 3.4.1

### ISSUE THREAD

**Issue by pgferrero** [team-moeller/better-access-charts#49]
Hi,

First off - great work.  My journey to get better charts in Access brought me here, and I'm glad it did.  Now I am just navigating through this code and I'm wondering if there are plans to update this db to use the latest Chartjs version - 3.4.1.   I was using this Chartjs version in a different project where I was testing connections to SQL Server via PHP then outputting to a chart using the latest version of Chartjs.  I tried simple updates to your code to change it to use the 3.4.1 version, but I was getting scripting errors.

Regardless, thanks for posting this code.

**Comment by pgferrero** [comment]
I do see (from the link https://github.com/nagix/chartjs-plugin-colorschemes/issues/28) that there are issues after Chartjs version v2.9.4 with chartjs-plugin-colorschemes compatibility.  Maybe you are waiting for that.

**Comment by pgferrero** [comment]
Hi - I see that the latest version is still using Chartjs version 2.9.4.   Any plans to utilize the latest Chartjs version - now 3.6.2 ?

**Comment by team-moeller** [comment]
I'm still waiting for the colorschemes plugin to be ready for version 3 of chart.js.
Why are you so keen on version 3 of Chart.js?
Are there any new features that you are missing?

**Comment by pgferrero** [comment]
Has it really been two months since you wrote this ... I must be in a time vacuum, lol.   I was deep into trying to migrate to this when I hit a snag.

The main feature that 3 has (3.4, I think) that is a necessary improvement over the prior version is subtitles.   These are part of a current reporting project that I am trying to migrate out of the Access chart object.  I'm trying to keep the same details in the reports (before using this to actually improve the reporting), and the subtitles are a required part of the report.  Not being able to use them is I think the only real impediment to transitioning to using better access charts instead of the Access chart object.

Add to this also something that Daniel Pineault mentioned, namely that the newer version of Chartjs uses HTML canvas which isn't supported by the existing webbrowser control in Access, and I think I am stuck for a while using the current Access chart object for this project 

This work is great, Thomas.  Hope Microsoft gets its act together and gets the webbrowser moved up in Access development, and the other group also moves the colorschemes forward, too.

**Comment by team-moeller** [comment]
I did some investigations here. At the end I found out that there is not a chance to run chart.js version 3.0.2 or higher with the access webbrowser control.
More details can be found on my blog:  https://blog.team-moeller.de/2023/02/better-access-charts-versuche-mit.html
So the only thing we can do is to wait for the new webbrowser control in Access.

**Comment by team-moeller** [comment]
I am on my way to implement chart.js version 3.0.2 together with the new webbrowser control in Access.
After this step I will work on version 4 of chart.js and also on the subtitle.

**Comment by team-moeller** [comment]
Release 3.20.01 supporting chart.js version 3

**Comment by team-moeller** [comment]
Hi @pgferrero !
For your information: Since version [3.26.07](https://github.com/team-moeller/better-access-charts/releases/tag/3.26.07) the subtitle is implemented in Better Access Charts.
