### ISSUE TITLE
Skalierung der Chart-Anzeige

### ISSUE THREAD

**Issue by KDGundermann** [team-moeller/better-access-charts#65]
Chart-JS scheint ein bestimmtes Breiten/Höhen Verhältnis vorausszusetzen.
Wenn man das Webcontrol relativ flach einstellt wird das Chart nicht skaliert, sondern es erscheinen unschöne Scroll-Balken:
![image](https://user-images.githubusercontent.com/208315/148214084-605cc1eb-2c7a-4a38-9f5b-4080741837a5.png)

**Comment by KDGundermann** [comment]
Problem: Wenn man ein Control mit Horizontaler/VertikalerAnker automatisch an die Größe des Formulars anpassen lässt,
so sind die Angaben von Control.Width und Control.Height zu Laufzeit falsch !!??
See also: [Access - Form or control width doesn't update](https://stackoverflow.com/questions/56146807/access-form-or-control-width-doesnt-update)

**Comment by KDGundermann** [comment]
Ich habe da eine Lösung, die erfordert aber etwas zusätzlichen Code und ich weiss nicht, ob der in BAC enthalten sein sollte..

**Comment by team-moeller** [comment]
Released with version 2.03.05
