### ISSUE TITLE
Chart height is always higher than Webcontrol

### ISSUE THREAD

**Issue by DuvelCorp** [team-moeller/better-access-charts#71]
Hi,

I am starting to play with your library (last version), and it is absolutely great but I have one annoying issue.
 
Whatever I try, ie modifying the size of the WebControl or the data to display, the resulting chart never fit perfectly into the WebBrowser control. 

I always have a vertical scroll appearing, and I have to scroll down to see the bottom LabelFieldNames.

So when first I generate charts I have something like this : 
![image](https://user-images.githubusercontent.com/33682764/148778123-149c6e43-0d95-4143-9018-658ea75939fd.png)

And once I scroll down : 
![image](https://user-images.githubusercontent.com/33682764/148778206-157f730a-7871-4965-bf15-f3a9fc11f173.png)

Is there something I have missed in the chart config to solve that behavior??
I searched your issue DB, but lot of folks ask in german here, and I am more comfortable with french ;)

Cheers

**Comment by KDGundermann** [comment]
Hi Duvel, 
yes I have already opened the isse #65 for this. (Sorry it is in german, it was more meant to give Thomas a hint that I am working on this issue.)
To summarize the solution:
- There will be a new property: AspectRatio (ChartJS is using a default aspect ration for width/height of 2) 
  So you can set the aspect ratio using the width/height of the browser control
- BUT!! In my test MSAccess does NOT update the width/height of a control if you resize the window !
- I have a solution but it needs some more code and I have to discuss with Thomas, if this should be included in BAC.

**Comment by DuvelCorp** [comment]
Ahhh thank you @KDGundermann , you actually answered another issue I have with a specific chart. 
I want to display a TOP 100 of users with horizontal-bar chart 
Using  something like :
`SELECT TOP 100 * FROM (SELECT username, COUNT(*) FROM entries  GROUP BY username ORDER BY COUNT(*) DESC)` 

and  for this my WB control is very tall, but whatever I try it only display a few RANDOM lines and only occupies the top space of the WB control.  So it is unusable, and this  W/H of 2 ratio is probably the culprit here.

**Comment by KDGundermann** [comment]
I have created a preview of the fix [here](https://github.com/KDGundermann/better-access-charts/tree/fix%2371)

This fix includes some new classes:
- FI_Form : tracks the resizing of a form
- FI_Controls: hold s a collection of FI_Control in a Firm
- FI_Control: holds the information of Top,Left,Width,Height of a control in a form

If you have questions to this implementation, pls ask

**Comment by DuvelCorp** [comment]
@KDGundermann 

Tried your fork. It works, but there are some issues.

---------------------------------------

First of all there are errors with **Pages** of a **TabControl** which don't  handle `.VerticalAnchor` and `.HorizontalAnchor` properties. And this generate errors when you have a tabcontrol on the form.
I adapted your code with a `Resume Next` Err_Handler to bypass it 

```
' --------------------------------------------------------------
' --- Initialization
' --------------------------------------------------------------

Friend Sub Init(ByVal ctlAcc As Access.Control, ByRef TheParentGetter As ParentGetter)

    On Error GoTo Err_Handler
    
    Set m_ParentGetter = TheParentGetter
    With ctlAcc
        m_Type = .ControlType
        m_Name = .Name
        m_DesignLeft = .Left
        m_DesignTop = .Top
        m_DesignWidth = .Width
        m_DesignHeight = .Height
        m_VerticalAnchor = .VerticalAnchor
        m_HorizontalAnchor = .HorizontalAnchor
    End With
    
Exit_Sub:
    Exit Sub
    
Err_Handler:
    ' MsgBox "FI_Control Init Error on " & ctlAcc.Name & vbCrLf & Err.Description
    ' Resume Exit_Sub
    Resume Next
    
End Sub
```
That's obviously not optimal and should be improved

---------------------------------------

Then...
I have created 2 charts with a large width (left) and tall height (right) to test your code. 
When I first start the form and generate charts, everything works as expected. The charts ocuppy the whole area of the Web Controls.

![image](https://user-images.githubusercontent.com/33682764/148908292-6da24564-db03-4faa-9e9c-b8ab93c39444.png)

However, as soon as you refresh the charts, you end up with this

![image](https://user-images.githubusercontent.com/33682764/148908392-05150865-0a5c-4fa8-8e46-bee5e8d8129b.png)

Even going into design mode and then form mode doesnt solve the issue (while it is supposed to clean the form variables).I do have this in my code:
```
    Private Sub Form_Close()
        Set m_FormInfo = Nothing
    End Sub
```
The only way to get back to first nice situation is to stop the code, close the form and relaunch everything. But it only works once. As soon as your refreshe the charts, its back.

---------------------

Also, it seems that you changed something else regarding the default color scheme, compared to original code. On my charts having several datasets, it is OK as each dataset is assigned with a color. But when I only have one dataset like in  the screenshots above, you can see that it colors the bars in different colors and then stop coloring after 12 bars. That's not what I want. I want the same color everywhere, just like the original code behaved. Not sure where to change this.

-----------------------
And finally, not sure if it is related to your code, but changing font size either on Default or on Datalabel,  has no effect at all
```
       myChartPers2.DataLabels.Font.Size = 6
       myChartPers2.Default.Font.Size = 6
```
Whatever I try, the fonts remain the same. This is very annoying for my TOP 50 vertical chart on the right, because it only display the names of odd bars and not even.



Room for improvement :)

Cheers

**Comment by KDGundermann** [comment]
Hi Duvel,

you have to redraw the Chart when the main Form changes its size. E.g.
```
Private Sub Form_Resize()
    CreateMyChart
    ' or .
   myChart.DrawChart
End Sub
```

**Comment by team-moeller** [comment]
issue closed due to inactivity
