### ISSUE TITLE
Rename Chart.ChartBackgroundColor

### ISSUE THREAD

**Issue by team-moeller** [team-moeller/better-access-charts#76]
Class Chart
Rename ChartBackgroundColor to BackgroundColor

Actual code: Chart.ChartBackgroundColor 
Future code: Chart.BackgroundColor

**Comment by NaincyKumariKnoldus** [comment]
Hey @team-moeller I have renamed it to BackgroundColor. I have raised a PR for this. Please review and merge my PR.
Thanks!
