### ISSUE TITLE
Blogpost: Introduce property "AspectRatio"

### ISSUE THREAD

**Issue by team-moeller** [team-moeller/better-access-charts#78]
Publish a blogpost and explain the new property "AspectRatio"

**Comment by KDGundermann** [comment]
we have to discuss how we should handle the problem that Access does not update the height / width attribute of the browser control.
- Option 1 : give a code example only in the docs how to handle the problem
- Option 2 : include code in BAC to show how to handle the problem

**Comment by team-moeller** [comment]
> we have to discuss how we should handle the problem that Access does not update the height / width attribute of the browser control.
> 
> * Option 1 : give a code example only in the docs how to handle the problem
> * Option 2 : include code in BAC to show how to handle the problem

Lets discuss this [here](https://github.com/team-moeller/better-access-charts/discussions/83)

**Comment by team-moeller** [comment]
Blogpost published on 16.01.2022

https://blog.team-moeller.de/2022/01/better-access-charts-das.html
