### ISSUE TITLE
Scatter-Chart 

### ISSUE THREAD

**Issue by RolfHeller** [team-moeller/better-access-charts#88]
I want t draw a scatter-chart of counted gas-quantities of a specific gas-meter (14) at irregular time-intervals by the following code:

Private Sub Bef_Grafik_Click()
    Dim myChart As BAC_Chart
    Set myChart = BAC.Chart(Me.ctlWebbrowser)
    'myChart.DrawChart
    'myChart.DataSource.ObjectName = "tbl_ZStand"
    myChart.DataSource.SQLStatement = "Select Z_ID, Z_S_Datum, Z_S_Stand from tbl_ZStand where Z_ID = 14 order by Z_S_Datum asc"
    myChart.DataSource.DataFieldNames = Array("Z_S_Datum", "Z_S_Stand")
    myChart.DataSource.LabelFieldName = "Z_ID"
    myChart.ChartType = chChartType.Scatter
    myChart.DrawChart
End Sub

I get the message: 
9 Index außerhalb des gültigen Bereichs.

Sciptfehler
dem Skript auf dieser Seite ist ein Fehler aufgetreten. 
Zeile: 24
Zeichen: 29
Fehler: '}' erwartet
Code: 0
URL: file:///C:/Users/Heller/AppData/Local/Temp/BetterAccessChart
_ctlWebbrowser.html
Möchten Sie, dass Scripts auf dieser Seite weiterhin ausgeführt werden? 
Ja Nein
S
How can I improve the reaction?

**Comment by team-moeller** [comment]
Hi @RolfHeller !
Can you provide a sample database with some demo data to reproduce the problem? 
I would love to have a deeper look at this.

**Comment by RolfHeller** [comment]
Hi, @***@***.***> !
Appended you will find the demo access file with included:
tbl_ZStand and a form called: frm_ZStand, that produces the reaction mentioned in GitHub fort he scatter-graph.

I see the difficulties, that the x-axes (Z_S_Datum) is a date-field and the field for the category (Z_ID) is numeric.

I'm expecting a graph as it can be produced in EXCEL (see the second append)

I'm waiting for your deeper look at it.

Von: Thomas Möller ***@***.***>
Gesendet: Freitag, 21. Januar 2022 18:16
An: team-moeller/better-access-charts ***@***.***>
Cc: RolfHeller ***@***.***>; Mention ***@***.***>
Betreff: Re: [team-moeller/better-access-charts] Scatter-Chart (Issue #88)


Hi @RolfHeller<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRolfHeller&data=04%7C01%7C%7C33c372e9b84d475b30b208d9dd01a502%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783821393782743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HhHWeFX6ud2%2FICOv31VmG7oLKUrmAA%2FcOLc2rw83ny4%3D&reserved=0> !
Can you provide a sample database with some demo data to reproduce the problem?
I would love to have a deeper look at this.

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fteam-moeller%2Fbetter-access-charts%2Fissues%2F88%23issuecomment-1018704906&data=04%7C01%7C%7C33c372e9b84d475b30b208d9dd01a502%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783821393782743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AnNhig%2FsSdv%2FhK9aaYX3zGrLMMi1%2Fjz0nVrzfeQJ8fg%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXNA7HDJQ2OJEIL3PM3ZN53UXGIDTANCNFSM5MP7JG7A&data=04%7C01%7C%7C33c372e9b84d475b30b208d9dd01a502%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783821393782743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VGIw6E3p%2FL9CuyjhHO4cV1Zw7yCak2f8HrI%2FuTOhuNo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C33c372e9b84d475b30b208d9dd01a502%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783821393782743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BLQkxDQKch3%2BivrZm6s7WEKZyOM%2BhQsXfqKWQpkuhd4%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C33c372e9b84d475b30b208d9dd01a502%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783821393782743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qt2l0sH%2FftsJlWfv%2FgF5SH6gVehFJ%2Bb5HFV4%2BGMhD1Y%3D&reserved=0>.

**Comment by team-moeller** [comment]
Hi @RolfHeller !
I had a first look. The recordcount is not always right so we have to do a rst.movelast to get the right number. This will fix the error "9 Index außerhalb des gültigen Bereichs." I will bring in this fix in the next release.
Related to the scatter chart we have a problem now when the expression for the x-axis is a date. In the short run I do not see a simple solution here. Maybe a simple line chart will be an alternative for your needs.

**Comment by RolfHeller** [comment]
Will line chart work with date (irregular time intervalls) as x-axis? In your examples line chart seems to work with self estabished categories only.

**Comment by team-moeller** [comment]
Have you tried it by yourself? ;-)

**Comment by team-moeller** [comment]
OK, I had another look into your database. First I imported alle modules from the latest release. So the error "9 Index außerhalb des gültigen Bereichs." does not happen anymore.
The I changed the code like this:
    Dim myChart As BAC_Chart
    Set myChart = BAC.Chart(Me.ctlWebbrowser)
    myChart.DataSource.SQLStatement = "Select Z_ID, Z_S_Datum, Z_S_Stand from tbl_ZStand where Z_ID = 2 order by Z_S_Datum asc"
    myChart.DataSource.DataFieldNames = Array("Z_S_Stand")
    myChart.DataSource.LabelFieldName = "Z_S_Datum"
    myChart.ChartType = chChartType.Line
    myChart.DrawChart
This created a linechart.

**Comment by team-moeller** [comment]
Conclusion:
- the technical error has gone with the latest release
- Related to the scatter chart we have a problem now when the expression for the x-axis is a date. We won't fix that.
- A linechart can be an alternative
=> I will close this issue.

**Comment by RolfHeller** [comment]
The solution you suggested does give a line chart with regular time intervals although the data in the database are not evenly distributed along the x-axis. Imo the representation of the data is misleading.

Perhaps you could use the scatter-chart with a conversion of time-data (on the x-axis) as decimal data (as EXCEL does). The difficulty remains to generate a x-axis with appropriate labels.

Thanks. Rolf
